<?php

/**
 * This file is automatically generated. Use 'phutil_mapper.php' to rebuild it.
 * @generated
 */

phutil_register_library_map(array(
  'class' =>
  array(
    'JavelinDivinerEngine' => 'engine',
  ),
  'function' =>
  array(
  ),
  'requires_class' =>
  array(
    'JavelinDivinerEngine' => 'DivinerEngine',
  ),
  'requires_interface' =>
  array(
  ),
));
